=== lisonge/gkd-subscription/lib/gkd.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer",
      "description": "当前订阅的版本,客户端更新订阅判断依据",
      "maximum": 9007199254740991,
      "minimum": 1
    },
    "author": {
      "type": "string",
      "description": "作者信息"
    },
    "description": {
      "type": "string",
      "description": "当前订阅描述"
    },
    "appList": {
      "type": "array",
      "description": "按APP分类的规则组",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "packageName": {
            "type": "string",
            "description": "APP的包名,不得与其他列表项重复"
          },
          "groupList": {
            "type": "array",
            "description": "规则组列表",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "integer",
                  "maximum": 9007199254740991,
                  "minimum": -9007199254740991,
                  "description": "标识当前列表项的唯一性,不得与其他列表项重复,填写后此项规则组可被用户启用或禁用\n填写后不得更改,否则更新订阅后规则组禁用记录将会错乱"
                },
                "description": {
                  "type": "string",
                  "description": "当前规则组描述"
                },
                "className": {
                  "type": "string",
                  "description": "匹配界面的类名,注意类名与APP包名完全不同,只是多数情况下以包名开头"
                },
                "ruleList": {
                  "type": "array",
                  "description": "规则列表",
                  "minItems": 1,
                  "items": {
                    "type": "object",
                    "properties": {
                      "selector": {
                        "type": "string",
                        "description": "规则的选择器"
                      },
                      "description": {
                        "type": "string",
                        "description": "当前规则的描述"
                      },
                      "className": {
                        "type": "string",
                        "description": "匹配界面的类名,不填则使用父对象的[className],但如果父对象没有此属性,则必填"
                      }
                    },
                    "required": ["selector"]
                  }
                }
              },
              "required": ["ruleList"]
            }
          }
        },
        "required": ["packageName", "groupList"]
      }
    }
  },
  "required": ["version", "appList"]
}

=== lisonge/gkd-subscription/src/ad-internal.gkd.json
{
  "$schema": "https://raw.githubusercontent.com/lisonge/gkd-subscription/main/lib/gkd.schema.json",
  "version": 1,
  "author": "https://github.com/lisonge",
  "description": "APP内部广告集合",
  "appList": [
    {
      "packageName": "com.zhihu.android",
      "groupList": [
        {
          "key": 0,
          "className": "com.zhihu.android.mix.activity.ContentMixProfileActivity",
          "description": "知乎回答页面-文章底部-卡片广告",
          "ruleList": [
            {
              "selector": "View[text$=`广告`] - View[text=`×`]"
            },
            {
              "selector": "TextView[text=`广告`] - Image"
            },
            {
              "selector": "TextView[text=`广告`] +2 Image"
            },
            {
              "selector": "TextView[text.length>0] + TextView[text*=`热度`] + View > Image"
            },
            {
              "selector": "View[text$=`的广告`] + View[text=`×`]"
            },
            {
              "selector": "TextView[text$=`的广告`] + TextView[text=`×`]"
            },
            {
              "selector": "View[text$=`的广告`] +2 View[text=`×`]"
            },
            {
              "selector": "TextView[text=`了解更多`] > TextView[text=`×`]"
            },
            {
              "selector": "TextView[text$=`的广告`] +2 TextView[text=`×`]"
            },
            {
              "selector": "TextView[text=`限时解锁`] +2 Image",
              "description": "盐选会员推荐"
            }
          ]
        },
        {
          "key": 1,
          "className": "com.zhihu.android.mix.activity.ContentMixProfileActivity",
          "description": "知乎回答页面-文章底部-文章推荐",
          "ruleList": [
            {
              "selector": "View[text$=`关注`][text*=`回答`] + View[text=`×`]"
            },
            {
              "selector": "View[text*=`的回答`][text*=`点赞`][text$=`评论`] + TextView + Image"
            },
            {
              "selector": "TextView[text*=`赞同`][text$=`评论`][text*=`·`] + TextView[text$=`专题精选`] + View[text=`×`]"
            }
          ]
        },
        {
          "key": 2,
          "className": "com.zhihu.android.ContentActivity",
          "description": "题目概览页面-回答列表-广告",
          "ruleList": [
            {
              "selector": "TextView[text=`确认`][id=`com.zhihu.android:id/confirm_uninterest`]",
              "description": "确认关闭广告按钮"
            },
            {
              "selector": "TextView[text=`撤销`] <2 LinearLayoutCompat + FrameLayout > TextView[id=`com.zhihu.android:id/uninterest_reason`]",
              "description": "不感兴趣理由按钮"
            },
            {
              "selector": "ViewGroup > TextView[text*=`广告`] +4 ImageView",
              "description": "广告关闭按钮-1"
            },
            {
              "selector": "ViewGroup > TextView[text*=`广告`] +2 ImageView",
              "description": "广告关闭按钮-2"
            }
          ]
        },
        {
          "className": "com.zhihu.android.app.ui.activity.MainActivity",
          "ruleList": [
            {
              "selector": "TextView[id=`com.zhihu.android:id/confirm_uninterest`]",
              "description": "确认关闭广告按钮"
            },
            {
              "selector": "TextView[id=`com.zhihu.android:id/uninterest_reason`]",
              "description": "不感兴趣理由按钮"
            },
            {
              "selector": "ViewGroup > TextView[text*=`的广告`] +2 ImageView"
            }
          ]
        },
        {
          "className": "com.zhihu.android.app.ui.activity.LauncherActivity",
          "description": "开屏广告",
          "ruleList": [
            {
              "selector": "TextView[id=`com.zhihu.android:id/btn_skip`]",
              "className": "com.zhihu.android.app.ui.activity.LauncherActivity"
            },
            {
              "selector": "TextView[id=`com.zhihu.android:id/btn_skip`]",
              "className": "com.zhihu.android.app.ui.activity.LaunchAdActivity"
            }
          ]
        }
      ]
    },
    {
      "packageName": "com.baidu.tieba",
      "groupList": [
        {
          "className": "com.baidu.tieba.tblauncher.MainTabActivity",
          "description": "开屏广告",
          "ruleList": [
            {
              "selector": "View[id=`com.byted.pangle:id/tt_splash_skip_btn`]"
            },
            {
              "selector": "TextView[text*=`广告`] - TextView[text^=`跳过`]"
            }
          ]
        },
        {
          "className": "com.baidu.tieba.tblauncher.MainTabActivity",
          "description": "主页推荐-广告",
          "ruleList": [
            {
              "selector": "TextView[text*=`广告`] < LinearLayout -2 RelativeLayout > TextView[text=`选择不喜欢理由`] + View"
            },
            {
              "selector": "TextView[text$=`广告`] < RelativeLayout <3 LinearLayout - LinearLayout >4 ImageView"
            }
          ]
        },
        {
          "className": "com.baidu.tieba.pb.pb.main.PbActivity",
          "ruleList": [
            {
              "selector": "TextView[text*=`广告`] < LinearLayout -2 RelativeLayout > TextView[text*=`选择不喜欢理由`] + View[index=1]"
            },
            {
              "selector": "RelativeLayout[id=`com.baidu.tieba:id/obfuscated`] > LinearLayout > FrameLayout[id=`com.baidu.tieba:id/obfuscated`] > ImageView"
            }
          ]
        }
      ]
    },
    {
      "packageName": "com.tencent.mm",
      "groupList": [
        {
          "className": "com.tencent.mm.plugin.sns.ui.SnsTimeLineUI",
          "description": "朋友圈-广告卡片",
          "ruleList": [
            {
              "selector": "TextView[text=`选择后将减少该类推荐`] + TextView[text=`确认`]"
            },
            {
              "selector": "TextView[text=`选择后将减少该类推荐`] + FrameLayout > ViewGroup > TextView[text.length>0]"
            },
            {
              "selector": "TextView[text*=`广告`] + TextView[text*=`广告`] + FrameLayout > LinearLayout[childCount=2] > LinearLayout[childCount=0] + LinearLayout[childCount=0]"
            },
            {
              "selector": "ImageView[contentDescription$=`的头像`] + LinearLayout > LinearLayout[childCount=2] > TextView[id!=null][text.length>0] + LinearLayout[id!=null][childCount=0]"
            }
          ]
        },
        {
          "className": "com.tencent.mm.plugin.webwx.ui.ExtDeviceWXLoginUI",
          "description": "其他设备登录界面-自动点击登录",
          "ruleList": [
            {
              "selector": "TextView[text=`取消登录`] - Button[text=`登录`]"
            }
          ]
        },
        {
          "className": "com.tencent.mm.ui.LauncherUI",
          "description": "微信聊天界面-红包",
          "ruleList": [
            {
              "selector": "TextView[text$=`的红包`] <2 LinearLayout < LinearLayout +2 ImageButton[contentDescription=`开`] + Button",
              "className": "com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyNotHookReceiveUI"
            },
            {
              "selector": "TextView[text$=`的红包`] >2 LinearLayout - ImageView < LinearLayout +2 RelativeLayout > TextView[text=`微信红包`]",
              "description": "红包描述下面有一行小字-**的红包"
            },
            {
              "selector": "RelativeLayout + LinearLayout >5 LinearLayout[childCount=1] - ImageView < LinearLayout +2 RelativeLayout > TextView[text=`微信红包`]",
              "description": "红包下面没有小字, 但是得和自己的红包区分开来"
            }
          ]
        },
        {
          "className": "com.tencent.mm.ui.LauncherUI",
          "description": "微信聊天界面-转账",
          "ruleList": [
            {
              "className": "com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyDetailUI",
              "selector": "ImageView[contentDescription=`返回按钮`]",
              "description": "红包领取结果页面-返回按钮"
            },
            {
              "selector": "TextView - Button[text=`收款`]",
              "className": "com.tencent.mm.plugin.remittance.ui.RemittanceDetailUI"
            },
            {
              "selector": "RelativeLayout + LinearLayout >4 TextView[text!=`已被接收`][text!=`已收款`][text!=`已收款待入账`] <2 LinearLayout < RelativeLayout <2 LinearLayout + RelativeLayout > TextView[text=`微信转账`]",
              "description": "注意:如果红包备注是[已被接收,已收款,已收款待入账],则无法区分"
            }
          ]
        },
        {
          "className": "com.tencent.mm.plugin.webview.ui.tools.SDKOAuthUI",
          "description": "第三方网页登录",
          "ruleList": [
            {
              "selector": "Button[text=`拒绝`] - Button[text=`允许`]"
            }
          ]
        }
      ]
    },
    {
      "packageName": "tv.danmaku.bili",
      "groupList": [
        {
          "className": "tv.danmaku.bili.ui.video.VideoDetailsActivity",
          "description": "视频播放页-评论区顶部-公告或推荐",
          "ruleList": [
            {
              "selector": "ImageView + TextView[id=`tv.danmaku.bili:id/content`] + ImageView[id=`tv.danmaku.bili:id/close`]"
            },
            {
              "selector": "ImageView + TextView[id=`tv.danmaku.bili:id/content`] + ImageView[id=`tv.danmaku.bili:id/close`]",
              "className": "com.bilibili.video.videodetail.VideoDetailsActivity",
              "description": "视频评论区-公告"
            },
            {
              "selector": "ImageView + TextView[id=`tv.danmaku.bili:id/content`] + ImageView[id=`tv.danmaku.bili:id/close`]",
              "className": "com.bilibili.lib.ui.GeneralActivity",
              "description": "用户动态评论区-公告"
            },
            {
              "selector": "ImageView + TextView[id=`tv.danmaku.bili:id/content`] + ImageView[id=`tv.danmaku.bili:id/close`]",
              "className": "com.bilibili.bangumi.ui.page.detail.BangumiDetailActivityV3",
              "description": "番剧评论区-公告"
            }
          ]
        },
        {
          "className": "tv.danmaku.bili.MainActivityV2",
          "description": "动态-综合-广告卡片",
          "ruleList": [
            {
              "selector": "TextView[id^=`tv.danmaku.bili:id/reason`]",
              "description": "点击广告关闭后的弹窗的列表项的第一个",
              "className": "com.bilibili.lib.ui.menu.a"
